apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: users-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/sidharthjs/argocd-config.git
    targetRevision: HEAD
    path: users
  destination: 
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
